<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Helhum\\Typo3Console\\' => array($typo3InstallDir . 'typo3conf/ext/typo3_console/Classes/Console'),
    'TYPO3\\CMS\\Typo3DbLegacy\\' => array($typo3InstallDir . 'typo3conf/ext/typo3db_legacy/Classes'),
);
